name: Verilator-Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install Build Dependencies
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S cmake ninja git curl zip unzip tar verilator

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake . -G Ninja -DCMAKE_BUILD_TYPE=Release -DVCPKG_BUILD_TYPE=release -DNYU_BUILD_TESTS=ON -DNYU_GEN_COV=ON 

      - name: Build
        run: cmake --build .

      - name: Test & Generate Coverage
        run: |
          ctest -C Release --output-on-failure
          sed -i -e '/\/share\//d' -e '/\/dv\//d' dv/*.dat
          verilator_coverage -write-info coverage.txt dv/*.dat

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
